name: Send Program Output via Email

on:
  push:
    branches:
      - master  # 対象のブランチ名

jobs:
  build-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v3

      - name: Cコードのコンパイル
        run: gcc -o hello_world hello_world.c

      - name: 実行権限の付与
        run: chmod +x hello_world

      - name: プログラムの実行と出力の取得
        id: run_program
        run: |
          output=$(./hello_world)
          echo "$output" > output.txt
          echo "::set-output name=program_output::$output"

      - name: メールの送信
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com  # SMTPサーバーのアドレス
          server_port: 587                  # SMTPサーバーのポート
          username: ${{ secrets.EMAIL_USERNAME }}  # シークレットに設定したユーザー名
          password: ${{ secrets.EMAIL_PASSWORD }}  # シークレットに設定したパスワード
          subject: 'プログラムの実行結果'
          body: ${{ steps.run_program.outputs.program_output }}
          to: recipient@example.com          # 受信者のメールアドレス
          from: sender@example.com           # 送信者のメールアドレス
          secure: true                       # SSL/TLSの使用有無
