name: Build and Send Email on Push

on:
  push:

jobs:
  build-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: プログラムをビルド
        run: gcc -o hello_world hello_world.c

      - name: 実行権限を付与
        run: chmod +x hello_world
      
      - name: プログラムを実行して出力を保存
        id: run_program
        run: |
          ./hello_world > output.txt 2> error.log || true
          echo "output<<EOF" >> $GITHUB_OUTPUT
          cat output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: エラーログの表示
        if: failure() || always()
        run: |
          echo "---- Error Log ----"
          cat error.log

      - name: メール送信
        uses: dawidd6/action-send-mail@v3
        with:
          # SMTPサーバーの設定（GitHub Secretsに設定してください）
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'ビルドと実行結果'
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          content_type: 'text/plain'
          body: |
            ${{ steps.run_program.outputs.output }}
